### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by vendethiel** [faux-combinator/perl#1]
No idea how to test/deep-compare objects in Perl5...

**Comment by no-longer-on-githu-b** [comment]
what is faux-combinator

**Comment by no-longer-on-githu-b** [comment]
help

**Comment by no-longer-on-githu-b** [comment]
Also `Test::More` has an `is_deeply` function which asserts deep equality.

**Comment by vendethiel** [comment]
It's called insanity: reimplementing the same library several times.

Thanks for Test::More! I'll look into it.

**Comment by vendethiel** [comment]
2547a8c0d4837a8eae3298d8c5267711d25e58fa + bc455c7c35361d39a7159875f9b8188dcd5bb697
